### ISSUE TITLE
curl结果不能通过管道传递？

### ISSUE THREAD

**Issue by al123xiaaaa** [web-terminal/web-terminal#2]
```bash
curl https://api.64clouds.com/v1/getServiceInfo?veid=1242548&api_key=private_xxxxxxx | js `console.log('输出：' + TerminalFeedArgs)`
```
这样一条命令没有办法在console.log输出curl获取到的结果

**Comment by al123xiaaaa** [comment]
![image](https://user-images.githubusercontent.com/6868760/102446629-35020280-4069-11eb-822e-a4f1b676dfb9.png)
原来是字符串解析报错了

**Comment by zoujunrong** [comment]
新版本通过自动编码和解码解决了数据传递问题
